# Generated by Django 5.1.1 on 2024-09-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0002_mainimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MainImage",
        ),
        migrations.AddField(
            model_name="courses",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
