# Generated by Django 5.1.1 on 2024-09-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0003_delete_mainimage_courses_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ITCourses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images_it/")),
                ("course_name", models.CharField(max_length=100)),
            ],
        ),
    ]
