# Generated by Django 5.1.1 on 2024-09-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0004_itcourses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itcourses",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
