# Generated by Django 5.1.1 on 2024-09-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0008_alter_logoimage_logo_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advanced",
            name="image",
            field=models.ImageField(
                null=True, upload_to="images/", verbose_name="Загрузите значок"
            ),
        ),
        migrations.AlterField(
            model_name="advanced",
            name="text",
            field=models.TextField(
                null=True, verbose_name="Укажите почему выбирают вас"
            ),
        ),
        migrations.AlterField(
            model_name="courses",
            name="course_name",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Укажите название курса"
            ),
        ),
        migrations.AlterField(
            model_name="courses",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to="images/",
                verbose_name="Загрузите фото направления",
            ),
        ),
        migrations.AlterField(
            model_name="itcourses",
            name="course_name",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Укажите название курса"
            ),
        ),
        migrations.AlterField(
            model_name="itcourses",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to="images/",
                verbose_name="Загрузите фото IT специальности",
            ),
        ),
    ]
