# Generated by Django 4.2.3 on 2024-11-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0013_news"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mission",
                    models.TextField(
                        default="", verbose_name="Напишите миссию института"
                    ),
                ),
            ],
            options={
                "verbose_name": "миссия",
                "verbose_name_plural": "миссии",
            },
        ),
        migrations.AlterModelOptions(
            name="news",
            options={"verbose_name": "новость", "verbose_name_plural": "новости"},
        ),
    ]
