# Generated by Django 5.1.2 on 2024-11-08 19:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0017_alter_itcourses_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itcourses",
            options={
                "permissions": [
                    ("can_add_it_courses", "Может добавлять IT курсы"),
                    ("can_change_it_courses", "Может изменять IT курсы"),
                    ("can_delete_it_courses", "Может удалять IT курсы"),
                    ("can_view_it_courses", "Может просматривать IT курсы"),
                ],
                "verbose_name": "IT направление",
                "verbose_name_plural": "IT направления",
            },
        ),
    ]
