# Generated by Django 5.1.2 on 2024-11-08 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0018_alter_itcourses_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advanced",
            options={
                "permissions": [
                    ("can_add_advanced", "Может добавлять продвижения"),
                    ("can_change_advanced", "Может изменять продвижения"),
                    ("can_delete_advanced", "Может удалять продвижения"),
                    ("can_view_advanced", "Может просматривать продвижения"),
                ],
                "verbose_name": "продвижение",
                "verbose_name_plural": "продвижения",
            },
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={
                "permissions": [
                    ("can_add_contact", "Может добавлять контакты"),
                    ("can_change_contact", "Может изменять контакты"),
                    ("can_delete_contact", "Может удалять контакты"),
                    ("can_view_contact", "Может просматривать контакты"),
                ],
                "verbose_name": "контакт",
                "verbose_name_plural": "контакты",
            },
        ),
        migrations.AlterModelOptions(
            name="courses",
            options={
                "permissions": [
                    ("can_add_courses", "Может добавлять направления"),
                    ("can_change_courses", "Может изменять направления"),
                    ("can_delete_courses", "Может удалять направления"),
                    ("can_view_courses", "Может просматривать направления"),
                ],
                "verbose_name": "направление",
                "verbose_name_plural": "направления",
            },
        ),
        migrations.AlterModelOptions(
            name="logoimage",
            options={
                "permissions": [
                    ("can_add_logo_image", "Может добавлять фото логотипа"),
                    ("can_change_logo_image", "Может изменять фото логотипа"),
                    ("can_delete_logo_image", "Может удалять фото логотипа"),
                    ("can_view_logo_image", "Может просматривать фото логотипа"),
                ],
                "verbose_name": "фото лого",
                "verbose_name_plural": "фото логотипа",
            },
        ),
        migrations.AlterModelOptions(
            name="mission",
            options={
                "permissions": [
                    ("can_add_mission", "Может добавлять миссии"),
                    ("can_change_mission", "Может изменять миссии"),
                    ("can_delete_mission", "Может удалять миссии"),
                    ("can_view_mission", "Может просматривать миссии"),
                ],
                "verbose_name": "миссия",
                "verbose_name_plural": "миссии",
            },
        ),
        migrations.AlterModelOptions(
            name="news",
            options={
                "permissions": [
                    ("can_add_news", "Может добавлять новости"),
                    ("can_change_news", "Может изменять новости"),
                    ("can_delete_news", "Может удалять новости"),
                    ("can_view_news", "Может просматривать новости"),
                ],
                "verbose_name": "новость",
                "verbose_name_plural": "новости",
            },
        ),
        migrations.AlterModelOptions(
            name="opendoor",
            options={
                "permissions": [
                    (
                        "can_add_open_door",
                        "Может добавлять информацию о причинах выбора",
                    ),
                    (
                        "can_change_open_door",
                        "Может изменять информацию о причинах выбора",
                    ),
                    (
                        "can_delete_open_door",
                        "Может удалять информацию о причинах выбора",
                    ),
                    (
                        "can_view_open_door",
                        "Может просматривать информацию о причинах выбора",
                    ),
                ],
                "verbose_name": "выбирают нас",
                "verbose_name_plural": "выбрали нас",
            },
        ),
        migrations.AlterModelOptions(
            name="welcome",
            options={
                "permissions": [
                    (
                        "can_add_welcome",
                        "Может добавлять описание для 'Добро пожаловать'",
                    ),
                    (
                        "can_change_welcome",
                        "Может изменять описание для 'Добро пожаловать'",
                    ),
                    (
                        "can_delete_welcome",
                        "Может удалять описание для 'Добро пожаловать'",
                    ),
                    (
                        "can_view_welcome",
                        "Может просматривать описание для 'Добро пожаловать'",
                    ),
                ],
                "verbose_name": "добро пожаловать",
                "verbose_name_plural": "добро пожаловать",
            },
        ),
    ]
