# Generated by Django 5.1.2 on 2024-11-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0020_alter_advanced_options_alter_contact_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="image2",
            field=models.ImageField(
                null=True, upload_to="news/", verbose_name="загрузите доп фото"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="image3",
            field=models.ImageField(
                null=True, upload_to="news/", verbose_name="загрузите доп фото"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(
                null=True, upload_to="news/", verbose_name="загрузите основное фото"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(
                max_length=100, null=True, verbose_name="укажите название новости"
            ),
        ),
    ]
