# Generated by Django 5.1.2 on 2024-11-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0021_news_image2_news_image3_alter_news_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="views",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Количество просмотров"
            ),
        ),
    ]
