# Generated by Django 5.1.2 on 2024-11-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0024_news_image3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="news/",
                verbose_name="загрузите доп фото",
            ),
        ),
    ]
