# Generated by Django 5.1.3 on 2024-11-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0027_remove_itcourses_some_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video_url',
            field=models.URLField(null=True, verbose_name='укажите ссылку с youtube'),
        ),
    ]
