# Generated by Django 5.1.3 on 2024-12-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0029_alter_news_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="lupic_ic",
            field=models.TextField(blank=True, null=True, verbose_name="Укажите Lupic"),
        ),
        migrations.AddField(
            model_name="itcourses",
            name="lupic_ic",
            field=models.TextField(blank=True, null=True, verbose_name="Укажите Lupic"),
        ),
    ]
