# Generated by Django 5.1.3 on 2024-12-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0030_courses_lupic_ic_itcourses_lupic_ic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='exam',
            field=models.CharField(default='teasdasdasdxt', max_length=100, null=True, verbose_name='есть ли вступительные экзамены'),
        ),
        migrations.AlterField(
            model_name='itcourses',
            name='exam',
            field=models.CharField(default='texfsdfsdfsdft', max_length=100, null=True, verbose_name='есть ли вступительные экзамены'),
        ),
    ]
