# Generated by Django 5.1.3 on 2024-12-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='student_live/', verbose_name='загрузите основное фото')),
                ('image2', models.ImageField(null=True, upload_to='student_live2/', verbose_name='загрузите доп фото')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='student_live3/', verbose_name='загрузите доп фото')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='укажите название мероприятия')),
                ('description', models.TextField(verbose_name='Укажите описание мероприятия')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='укажите ссылку с youtube')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0, null=True, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'мероприятие',
                'verbose_name_plural': 'мероприятия',
            },
        ),
    ]
