# Generated by Django 5.1.2 on 2024-11-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about_us", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="About_AUP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="aup/", verbose_name="загрузите фото"),
                ),
                (
                    "position",
                    models.CharField(max_length=100, verbose_name="укажите должность"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="укажите инициалы"),
                ),
                (
                    "description",
                    models.TextField(verbose_name="укажите информацию о человеке"),
                ),
            ],
            options={
                "verbose_name": "должность AUP",
                "verbose_name_plural": "должности AUP",
            },
        ),
        migrations.AlterModelOptions(
            name="about_text",
            options={
                "verbose_name": "описание о вузе",
                "verbose_name_plural": "описания о вузе",
            },
        ),
    ]
