# Generated by Django 5.1.2 on 2024-11-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about_us", "0002_about_aup_alter_about_text_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="About_PPC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="ppc/", verbose_name="загрузите фото преподавателя"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="укажите инициалы преподавателя"
                    ),
                ),
                (
                    "course",
                    models.CharField(
                        max_length=100, verbose_name="Укажите какие курсы он преподает"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="укажите информацию о преподавателе"),
                ),
            ],
            options={
                "verbose_name": "преподаватель",
                "verbose_name_plural": "преподаватели",
            },
        ),
    ]
