# Generated by Django 5.1.2 on 2024-11-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about_us", "0003_about_ppc"),
    ]

    operations = [
        migrations.AddField(
            model_name="about_aup",
            name="achievements",
            field=models.TextField(
                null=True, verbose_name="какие достижения вы достигли"
            ),
        ),
        migrations.AddField(
            model_name="about_aup",
            name="education",
            field=models.TextField(null=True, verbose_name="укажите образование"),
        ),
        migrations.AddField(
            model_name="about_aup",
            name="qualification",
            field=models.TextField(
                null=True, verbose_name="укажите повышение квалификации"
            ),
        ),
        migrations.AddField(
            model_name="about_aup",
            name="sertificate_url",
            field=models.URLField(
                null=True, verbose_name="укажите ссылку на свой сертификат из DRIVE"
            ),
        ),
        migrations.AddField(
            model_name="about_ppc",
            name="achievements",
            field=models.TextField(
                null=True, verbose_name="какие достижения вы достигли"
            ),
        ),
        migrations.AddField(
            model_name="about_ppc",
            name="education",
            field=models.TextField(null=True, verbose_name="укажите образование"),
        ),
        migrations.AddField(
            model_name="about_ppc",
            name="qualification",
            field=models.TextField(
                null=True, verbose_name="укажите повышение квалификации"
            ),
        ),
        migrations.AddField(
            model_name="about_ppc",
            name="sertificate_url",
            field=models.URLField(
                null=True, verbose_name="укажите ссылку на свой сертификат из DRIVE"
            ),
        ),
    ]
