# Generated by Django 5.1.3 on 2024-12-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200, verbose_name='Добавьте вопрос')),
                ('answer_text', models.URLField(verbose_name='Вставьте ссылку на документ к вопросу из DRIVE')),
            ],
        ),
        migrations.CreateModel(
            name='EditionInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200, verbose_name='Добавьте вопрос')),
                ('answer_text', models.URLField(verbose_name='Вставьте ссылку на документ к вопросу из DRIVE')),
            ],
        ),
    ]
