# Generated by Django 5.1.2 on 2024-11-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_doc",
                    models.CharField(
                        max_length=100,
                        null=True,
                        verbose_name="укажите название документа",
                    ),
                ),
                (
                    "file_doc",
                    models.FileField(
                        null=True,
                        upload_to="documents/license/",
                        verbose_name="загрузите документ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лицензия",
                "verbose_name_plural": "Лицензии",
            },
        ),
        migrations.CreateModel(
            name="Normative_legal_acts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_doc",
                    models.CharField(
                        max_length=100, verbose_name="укажите название документа"
                    ),
                ),
                (
                    "file_doc",
                    models.FileField(
                        upload_to="documents/normative_legal_act/",
                        verbose_name="загрузите документ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Нормативно правовой акт",
                "verbose_name_plural": "Нормативно правовые акты",
            },
        ),
        migrations.CreateModel(
            name="Organizational_structure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_doc",
                    models.CharField(
                        max_length=100, verbose_name="укажите название документа"
                    ),
                ),
                (
                    "file_doc",
                    models.FileField(
                        upload_to="documents/normative_legal_act/",
                        verbose_name="загрузите документ",
                    ),
                ),
            ],
            options={
                "verbose_name": "организационная структура",
                "verbose_name_plural": "организационные структуры",
            },
        ),
        migrations.DeleteModel(
            name="Test",
        ),
    ]
