# Generated by Django 5.1.2 on 2024-11-09 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_license_normative_legal_acts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="normative_legal_acts",
            name="file_doc",
        ),
        migrations.CreateModel(
            name="Category_acts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_doc_act",
                    models.CharField(
                        max_length=100, verbose_name="укажите название документа"
                    ),
                ),
                (
                    "file_doc",
                    models.FileField(
                        upload_to="documents/other_doc/",
                        verbose_name="загрузите документ",
                    ),
                ),
                (
                    "category_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_acts",
                        to="documents.normative_legal_acts",
                        verbose_name="выберите категорию",
                    ),
                ),
            ],
        ),
    ]
