# Generated by Django 5.1.3 on 2024-11-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='укажите деятельность отдела')),
            ],
            options={
                'verbose_name': 'деятельность отдела',
                'verbose_name_plural': 'деятельности отдела',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='international_department_employee/')),
                ('name', models.CharField(max_length=100, verbose_name='Укажите имя сотрудника')),
                ('position', models.CharField(max_length=100, verbose_name='Укажите должность сотрудника')),
                ('email_employe', models.EmailField(max_length=254, verbose_name='укажите почту сотрудника')),
                ('number', models.CharField(max_length=100, verbose_name='укажите номер телефона')),
                ('address', models.CharField(max_length=100, verbose_name='укажите адрес')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
            ],
            options={
                'verbose_name': 'фотография',
                'verbose_name_plural': 'фотографии',
            },
        ),
        migrations.CreateModel(
            name='GeneralInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='укажите общую информацию')),
            ],
            options={
                'verbose_name': 'общую информацию',
                'verbose_name_plural': 'общая информация',
            },
        ),
        migrations.CreateModel(
            name='RegulatoryDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_document', models.URLField(verbose_name='вставьте ссылку на документ')),
            ],
            options={
                'verbose_name': 'документ',
                'verbose_name_plural': 'документы',
            },
        ),
        migrations.CreateModel(
            name='ShortStoryDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='укажите краткую историю')),
            ],
            options={
                'verbose_name': 'краткую историю',
                'verbose_name_plural': 'краткая история',
            },
        ),
    ]
